/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutJoelRouteImport } from './routes/about-joel'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogAuthorJoelJorgensenRouteImport } from './routes/blog.author.joel-jorgensen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutJoelRoute = AboutJoelRouteImport.update({
  id: '/about-joel',
  path: '/about-joel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAuthorJoelJorgensenRoute = BlogAuthorJoelJorgensenRouteImport.update({
  id: '/blog/author/joel-jorgensen',
  path: '/blog/author/joel-jorgensen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-joel': typeof AboutJoelRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/author/joel-jorgensen': typeof BlogAuthorJoelJorgensenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-joel': typeof AboutJoelRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/author/joel-jorgensen': typeof BlogAuthorJoelJorgensenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-joel': typeof AboutJoelRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/author/joel-jorgensen': typeof BlogAuthorJoelJorgensenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-joel'
    | '/contact'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/author/joel-jorgensen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-joel'
    | '/contact'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/blog/$slug'
    | '/blog'
    | '/blog/author/joel-jorgensen'
  id:
    | '__root__'
    | '/'
    | '/about-joel'
    | '/contact'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/author/joel-jorgensen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutJoelRoute: typeof AboutJoelRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogAuthorJoelJorgensenRoute: typeof BlogAuthorJoelJorgensenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-joel': {
      id: '/about-joel'
      path: '/about-joel'
      fullPath: '/about-joel'
      preLoaderRoute: typeof AboutJoelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/author/joel-jorgensen': {
      id: '/blog/author/joel-jorgensen'
      path: '/blog/author/joel-jorgensen'
      fullPath: '/blog/author/joel-jorgensen'
      preLoaderRoute: typeof BlogAuthorJoelJorgensenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutJoelRoute: AboutJoelRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogAuthorJoelJorgensenRoute: BlogAuthorJoelJorgensenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
